//
//  dictUA.swift
//  Budget Tracker
//
//  Created by Mikhailo Dovhyi on 20.03.2022.
//  Copyright © 2022 Misha Dovhiy. All rights reserved.
//

import Foundation
import UIKit

struct localizationDictUA {

    static let dictUA: [String:String] = [
        "You already have PRO version":"У вас вже є PRO версія",
        "Error saving purchase":"Помилка збереження покупки",
        "Payment not found":"Платіж не знайдено",
        "More":"Бiльше",
        "No transactions history":"Порожньо",
        "Privacy policy":"Політика конфіденційності",
        "Price":"Ціна",
        "Free Trial":"Безкоштовне випробування",
        "Restore purchase":"Відновити покупку",
        "Buy Pro":"Купити Pro",
        "App website":"Сайт додатку",
        "Developer website":"Сайт розробника",
        "Set":"Встановити",
        "Passcode timeout":"Час очікування пароля",
        "Select color":"Оберіть колір",
        "Access settings": "Налаштування доступу",
        "Ask passcode in": "Запитувати пароль через",
        "seconds": "сек",
        "Support message":"Підтримка",
        "Period Balance":"Баланс за період",
        "Balance":"Баланс",
        "Filtering":"Фільтрування",
        "Date":"Дата",
        "Category":"Категорія",
        "Category search":"Пошук за категоріями",
        "Sort":"Сортування",
        "debt":"борг",
        "Sun":"нед",
        "Sat":"суб",
        "Fri":"пт",
        "Thu":"чт",
        "Wed":"ср",
        "Tue":"вт",
        "Mon":"пн",
        "Total payed:":"Всього сплачено:",
        "Rest:":"Залишок:",
        "Amount":"Сума",
        "Amount to pay:":"Сума для cплати:",
        "Amount to pay":"Сума для cплати",
        "Expired!":"Термін\nзакінчився!",
        "Enter Passcode":"Введіть пароль",
        "Total":"Всього",
        "No data":"Порожньо",
        "Total:":"Всього:",
        "No transactions":"Жодних транзакцій",
        "not found":"не знайдено",
        "Category not found":"Категорію не знайдено",
        "User not found" : "Користувач не знайдений",
        "Forgot password" : "Забули пароль",
        "Enter your username" : "Введіть своє ім'я користувача",
        "Username" : "Ім'я користувача",
        "Change Email" : "Змінити пошту",
        "Change email" : "Змінити пошту",
        "Email":"електронна адреса",
        "Log out" : "Вийти",
        "Restoration code would be sent on: " : "Код буде надіслано: ",
        "Send code" : "Надіслати код",
        "Send" : "Надіслати",
        "Cancel" : "Скасувати",
        "Wrong password" : "Неправильний пароль",
        "Enter password" : "Введіть пароль",
        "Enter username" : "Введіть ім'я користувача",
        "Enter username or email" : "Введіть ім'я користувача або електронну адресу",
        "Username or email" : "Ім'я або поштa",
        "Change password" : "Змінити пароль",
        "Repeat password" : "Повторити пароль",
        "Your email has been changed" : "Вашу електронну адресу було змінено",
        "Enter your new email" : "Введіть нову електронну пошту",
        "You have entered: " : "Ви ввели: ",
        "Wrong code!" : "Невірний код!",
        "We have sent 4-digit resoration code on your email" : "Ми надіслали 4-значний код на вашу електронну пошту",
        "Restoration code" : "Код відновлення",
        "Code" : "Код",
        "You will receive restoration code" : "Ви отримаєте код відновлення",
        "Create your new password" : "Створіть новий пароль",
        "Enter your old password" : "Введіть свій старий пароль",
        "Old password" : "Старий пароль",
        "Enter":"Введiть",

    
        "Categories" : "Категорії",
        "Fetching" : "Оновлення",
        "Account" : "Профіль",
        "Statistic" : "Статистика",
        "New category" : "Нова категорія",
        "Loading" : "Завантаження",
        "Done" : "Готово",
        "Internet error" : "Помилка з'єднання",
        "Try again later" : "Спробуйте ще раз пізніше",
        "Wrong" : "Неправильно",
        "Creating" : "Створення",
        "Enter valid email" : "Неправильна адреса пошти",
        "Enter valid email address" : "Введіть дійсну адресу електронної пошти",
        "With correct email address you could restore your password in the future" : "З правильною адресою електронної пошти ви можете відновити свій пароль у майбутньому",

        "You have reached the maximum amount of usernames" : "Ви досягли максимальної кількості імен користувачів",
        "Update to Pro" : "Оновiться до Pro версії",
        "to create new username" : "щоб створити нове і'я користувача",
        "already exists" : "вже існує",
        "Passwords not match" : "Паролі не збігаються",
        "Don't have an account" : "Немає аккаунту",
        "Already have an account" : "Вже є аккаунт",

        "Log in" : "Увійти",
        "Create username" : "Введіть ім'я користувача",
        "Enter your email" : "Введіть свою електронну адресу",
        "Create password" : "Створити пароль",
        "Confirm password" : "Підтвердiть пароль",
        "Password" : "Пароль",
        "Email not found" : "Електронну пошту не знайдено",
        "Sign in" : "Увійти",
        "Select user" : "Виберіть користувача",
        "Downloading" : "Завантаження",
        "Wellcome" : "Ласкаво просимо",
        "Wellcome to Budget Tracker" : "Ласкаво просимо до Budget Tracker",
        "Demo data has been created" : "Демо дані створено",
        "No Transactions" : "Немає транзакцій",
        "Local data" : "Оффлайн дані",
        "Pro trial is over" : "Pro випробування закінчено",
        "Filter" : "Фільтр",
        "Error sending data" : "Помилка надсилання даних",
        "Sending" : "Відправка",
        "Your password has been changed" : "Ваш пароль було змінено",
        "Edit" : "Редагувати",
        "Delete" : "Видалити",
        "Error deleting transaction" : "Помилка видалення транзакції",
        "Adding" : "Додавання",
        "adding" : "додавання",
        "Short comment" : "Короткий коментар",
        "Unknown" : "Невідомо",
        "Jan" : "Січ",
        "Feb" : "Лют",
        "Mar" : "Бер",
        "Apr" : "Квіт",
        "May" : "Трав",
        "June" : "Чер",
        "July" : "Лип",
        "Aug" : "Серп",
        "Sept" : "Вер",
        "Oct" : "Жовт",
        "Nov" : "Лист",
        "Dec" : "Груд",
        "Months" : "Місяць",
        "Years" : "Рiк",
        "Debts" : "Борги",
        
        "Jul" : "Лип",
        "Jun" : "Чер",
        "Sep" : "Вер",
        
        "All transaction" : "Усі транзакції",
        "Saving" : "Збереження",
        "Most used" : "Найбільш використовуванi",
        "Name" : "Ім'я",
        "Default" : "За замовчуванням",
        "Deleting" : "Видалення",

        "Income": "Дохiд",
        "Incomes" : "Дохiд",
        "Expenses" : "Витрати",
        "for" : "для",

        "No" : "Немає",
        "Data" : "Даних",
        
        "Create an account" : "Створити аккаунт",
        "Unknown category" : "Невідома категорія",
        "Settings" : "Налаштування",
        "Security" : "Безпека",
        "Appearance" : "Зовнішній вигляд",
        "Primary color" : "Основний колір",
        "Language" : "Мова",
        "Passcode" : "Пароль",
        "passcode" : "Пароль",
        "Change passcode" : "Змінити пароль",
        "Support" : "Підтримка",
        "Passcode has been setted" : "Пароль встановлено",
        "Passcodes don't match" : "Паролі не збігаються",
        "Repeat" : "Повторити",
        "Create" : "Створити",
        "Success" : "Успіх",
        "Error" : "Помилка",
        "Thank you" : "Дякую",
        "Your message has been sent" : "Ваше повідомлення надіслано",
        "Set icon" : "Встановити значок",
        "Next":"Далi",

        "Due date" : "Нагадування про сплату",
        "Due date has expired" : "Термін сплати закінчився",
        "Payment reminder": "Нагадування про оплату",
        "For category":"Для категорії",
        "notification" : "повідомлення",
        "Get notification reminder on specific date" : "Отримати сповіщення про оплату",
        "Unset" : "Не налаштовано",
        "Local notification not added" : "Локальне сповіщення не додано",

        "Logging in" : "Вхід",
        "All fields are required" : "Всі поля обов'язкові для заповнення",

        "All Time" : "Весь час",
        "This Month" : "Цей місяць",
        "Today" : "Сьогодні",
        "Yesterday" : "Вчора",
        "Custom" : "Обрати",

        "End" : "Кінець",
        "Start" : "Почати",
        "Selected" : "Вибраний",
        "of" : "з",
        "Error editing" : "Помилка редагування",
        "Sign in to use pro version across all your devices" : "Увійдіть щоб використовувати професійну версію на всіх своїх пристроях",
        "Access denied" : "Доступ заборонено",
        "Trial has been started successfully" : "Розпочато випробувальний період",
        "You have already purchased pro version" : "Ви вже придбали PRO версію",
        "Permission denied" : "У дозволі відмовлено",
        "You have already tried trial version" : "Ви вже спробували пробну версію",
        "Reminders for debts" : "Нагадування про борги",
        "Set notification reminders" : "Встановити нагадування",
        "Transfer data" : "Данi мiж аккаунтами",
        "Transfer transactions and categories between accounts" : "Переносьте транзакції та категорії між аккаунтами",
        "App storage increes" : "Збільште обсяг пам'яті програми",
        "Create up to 15 accounts for email\n\nStores data about categories usage" : "Стоворюйте до 15 облікових записів для електронної пошти\n\nДодаток зберігає дані про використання категорій",

        "Pro version available across all your devices" : "Pro-версія доступна на всіх ваших пристроях",
        "Payment failed" : "Платіж не вдалося",
        "Sign in required" : "Потрібна авторизація",
        "Calendar":"Календар",
        "Monthly repeat":"Повторювати щомiсяця",
        "Add transaction":"Додати транзакцію",
        "Payment reminders":"Нагадування про платежі",
        "Payment reminders ":"Нагадування",
    ]
}
