//
//  IconList.swift
//  Budget Tracker
//
//  Created by Mikhailo Dovhyi on 17.12.2021.
//  Copyright © 2021 Misha Dovhiy. All rights reserved.
//

import UIKit

class Icons {
    
    var icons:[IconsData]  {
        get {

            return [
                IconsData(sectionName: "", data: allIcons),
             //   IconsData(sectionName: "other", data: otherSection),
             //   IconsData(sectionName: "other", data: otherTwoSection)
                
            ]
        }
    }
    
    private var allIcons:[String] {
        return [
            "display.2",
                        "dollarsign.square.fill",
                        "drop.fill",
                        "ear.and.waveform",
                        "earbuds",
                        "ellipsis.curlybraces",
                        "ellipsis",
                        "envelope.fill",
                        "esim.fill",
                        "exclamationmark.triangle.fill",
                        "eye.fill",
                        "eyebrow",
                        "eyeglasses",
                        "eyes.inverse",
                        "face.smiling.fill",
                        "ferry.fill",
                        "figure.stand",
                        "figure.walk",
                        "figure.wave",
                        "film",
                        "flag.fill",
                        "flag.filled.and.flag.crossed",
                        "flame.circle.fill",
                        "flame.fill",
                        "flashlight.on.fill",
                        "folder.fill",
                        "folder",
                        "fork.knife",
                        "fuelpump.fill",
                        "gamecontroller.fill",
                        "gear.circle.fill",
                        "gearshape.2.fill",
                        "gearshape.fill",
                        "gift.fill",
                        "giftcard.fill",
                        "globe.americas.fill",
                        "globe.europe.africa.fill",
                        "graduationcap.fill",
                        "grid.circle.fill",
                        "guitars.fill",
                        "gyroscope",
                        "hammer.fill",
                        "hand.point.up.braille.fill",
                        "hand.point.up.left.fill",
                        "hand.raised.fill",
                        "hand.tap.fill",
                        "hands.clap.fill",
                        "hare.fill",
                        "headphones",
                        "heart.rectangle.fill",
                        "heart.slash.fill",
                        "heart.text.square.fill",
                        "hourglass.bottomhalf.filled",
                        "house.fill",
                        "ivfluid.bag.fill",
                        "key.fill",
                        "keyboard.fill",
                        "ladybug.fill",
                        "leaf.fill",
                        "lightbulb.fill",
                        "line.3.horizontal",
                        "lock.fill",
                        "lock.open.fill",
                        "lungs.fill",
                        "macwindow",
                        "magazine.fill",
                        "mail.fill",
                        "map.fill",
                        "mappin",
                        "memorychip.fill",
                        "mic.fill",
                        "mic.square.fill",
                        "minus.plus.batteryblock.fill",
                        "moon.fill",
                        "moon.stars.fill",
                        "moon.zzz.fill",
                        "mouth.fill",
                        "music.mic.circle.fill",
                        "music.mic",
                        "music.note.list",
                        "music.note",
                        "music.quarternote.3",
                        "mustache.fill",
                        "newspaper.fill",
                        "nose.fill",
            
            
            
            
            
            "number.square.fill",
            "paintbrush.fill",
            "paintbrush.pointed.fill",
            "paintpalette.fill",
            "paperclip",
            "paperplane.fill-1",
            "paperplane.fill",
            "paperplane",
            "pawprint.fill",
            "pc",
            "peacesign-1",
            "peacesign",
            "person.3.sequence.fill",
            "person.fill.questionmark",
            "person.fill",
            "person.text.rectangle.fill",
            "phone.and.waveform.fill",
            "phone.fill",
            "photo.artframe",
            "photo.fill",
            "photo.tv",
            "pianokeys.inverse",
            "pills.fill",
            "pin.fill",
            "play.rectangle.fill",
            "plus",
            "poop",
            "power.circle.fill",
            "powerplug.fill",
            "powersleep",
            "printer.fill",
            "puzzlepiece.extension.fill",
            "quote.bubble.fill",
            "rectangle.and.hand.point.up.left.fill",
            "rectangle.filled.and.hand.point.up.left",
            "rectangle.split.3x3.fill",
            "scanner.fill",
            "scissors",
            "screwdriver.fill",
            "scroll.fill",
            "scroll",
            "sdcard.fill",
            "shield.fill",
            "simcard.fill",
            "sparkle",
            "sparkles",
            "speaker.wave.3.fill",
            "stethoscope.circle.fill",
            "stethoscope",
            "stopwatch.fill",
            "suit.club.fill",
            "suit.diamond.fill",
            "suit.heart.fill",
            "suit.spade.fill",
            "suitcase.cart.fill",
            "suitcase.fill",
            "sun.haze.fill",
            "sun.max.fill",
            "tag.fill",
            "takeoutbag.and.cup.and.straw.fill",
            "terminal.fill",
            "testtube.2",
            "text.below.photo.fill",
            "text.book.closed.fill",
            "text.quote",
            "theatermasks.fill",
            "thermometer.snowflake",
            "ticket.fill",
            "timeline.selection",
            "tortoise.fill",
            "tram.fill",
            "trash.fill",
            "trash",
            "tray.fill",
            "tray",
            "tshirt.fill",
            "tv.fill",
            "tv.inset.filled",
            "umbrella.fill",
            "unknown",
            "viewfinder.circle.fill",
            "waveform.and.mic",
            "waveform.path.ecg.rectangle.fill",
            "waveform.path",
            "waveform",
            "wrench.and.screwdriver.fill",
            "wrench.fill",
            "xmark.circle",
            
            
            
            
            
            
            
            
            
            "airplane.departure",
            "airplane",
            "alarm.fill",
            "align.horizontal.center.fill",
            "align.vertical.bottom.fill",
            "ant.fill",
            "atom",
            "bag.circle.fill",
            "bag.fill",
            "bag",
            "bandage.fill",
            "banknote.fill",
            "battery.100",
            "battery.25",
            "battery.50",
            "battery.75",
            "bed.double.fill",
            "bell.badge.fill",
            "bell.badge",
            "bell.fill",
            "binoculars.fill-1",
                            "binoculars.fill",
                            "bolt.batteryblock.fill",
                           "bolt.horizontal.fill",
                            "bolt.square.fill",
                            "books.vertical.fill",
                            "briefcase.fill",
                            "bubble.left.and.bubble.right.fill",
                            "bubble.left.fill",
                            "building.2.fill",
                            "building.columns.circle.fill-1",
                            "building.columns.circle.fill",
                            "building.columns.fill",
                            "burn",
                            "bus.fill",
                            "bus",
                            "camera.fill",
                            "camera.viewfinder",
                            "candybarphone",
                            "captions.bubble.fill",
                            "car.fill",
                            "cart.circle.fill",
                            "cart.fill",
                            "cart",
                            "character.book.closed.fill",
                            "chart.pie.fill",
                            "checkerboard.rectangle",
                            "checkmark",
                            "chevron.left.forwardslash.chevron.right",
                            "chevron.up.circle",
                            "clock.fill",
                            "cloud.bolt.fill",
                            "cloud.bolt.rain.fill",
                            "cloud.rain.fill",
                            "cloud.snow.fill",
                            "comb.fill",
                            "cpu.fill",
                            "cpu",
                            "creditcard.fill",
                            "crown.fill",
                            "cube.fill",
                            "cup.and.saucer.fill",
                            "curlybraces.square.fill",
                            "cylinder.split.1x2.fill",
                            "desktopcomputer",
                            "dice.fill",
                            "die.face.1.fill",
                            "die.face.2.fill",
                            "die.face.3.fill",
                            "die.face.4.fill",
                            "die.face.5.fill",
                            "die.face.6.fill",
                        
        ]
    }
    
    
    private var otherTwoSection:[String] {
        return [
            "number.square.fill",
            "paintbrush.fill",
            "paintbrush.pointed.fill",
            "paintpalette.fill",
            "paperclip",
            "paperplane.fill-1",
            "paperplane.fill",
            "paperplane",
            "pawprint.fill",
            "pc",
            "peacesign-1",
            "peacesign",
            "person.3.sequence.fill",
            "person.fill.questionmark",
            "person.fill",
            "person.text.rectangle.fill",
            "phone.and.waveform.fill",
            "phone.fill",
            "photo.artframe",
            "photo.fill",
            "photo.tv",
            "pianokeys.inverse",
            "pills.fill",
            "pin.fill",
            "play.rectangle.fill",
            "plus",
            "poop",
            "power.circle.fill",
            "powerplug.fill",
            "powersleep",
            "printer.fill",
            "puzzlepiece.extension.fill",
            "quote.bubble.fill",
            "rectangle.and.hand.point.up.left.fill",
            "rectangle.filled.and.hand.point.up.left",
            "rectangle.split.3x3.fill",
            "scanner.fill",
            "scissors",
            "screwdriver.fill",
            "scroll.fill",
            "scroll",
            "sdcard.fill",
            "shield.fill",
            "simcard.fill",
            "sparkle",
            "sparkles",
            "speaker.wave.3.fill",
            "stethoscope.circle.fill",
            "stethoscope",
            "stopwatch.fill",
            "suit.club.fill",
            "suit.diamond.fill",
            "suit.heart.fill",
            "suit.spade.fill",
            "suitcase.cart.fill",
            "suitcase.fill",
            "sun.haze.fill",
            "sun.max.fill",
            "tag.fill",
            "takeoutbag.and.cup.and.straw.fill",
            "terminal.fill",
            "testtube.2",
            "text.below.photo.fill",
            "text.book.closed.fill",
            "text.quote",
            "theatermasks.fill",
            "thermometer.snowflake",
            "ticket.fill",
            "timeline.selection",
            "tortoise.fill",
            "tram.fill",
            "trash.fill",
            "trash",
            "tray.fill",
            "tray",
            "tshirt.fill",
            "tv.fill",
            "tv.inset.filled",
            "umbrella.fill",
            "unknown",
            "viewfinder.circle.fill",
            "waveform.and.mic",
            "waveform.path.ecg.rectangle.fill",
            "waveform.path",
            "waveform",
            "wrench.and.screwdriver.fill",
            "wrench.fill",
            "xmark.circle",
        ]
    }
    
    
    
    
    private var animalsSection:[String] {
        return [
            "airplane.departure",
            "airplane",
            "alarm.fill",
            "align.horizontal.center.fill",
            "align.vertical.bottom.fill",
            "ant.fill",
            "atom",
            "bag.circle.fill",
            "bag.fill",
            "bag",
            "bandage.fill",
            "banknote.fill",
            "battery.100",
            "battery.25",
            "battery.50",
            "battery.75",
            "bed.double.fill",
            "bell.badge.fill",
            "bell.badge",
            "bell.fill",
            "binoculars.fill-1",
                            "binoculars.fill",
                            "bolt.batteryblock.fill",
                           "bolt.horizontal.fill",
                            "bolt.square.fill",
                            "books.vertical.fill",
                            "briefcase.fill",
                            "bubble.left.and.bubble.right.fill",
                            "bubble.left.fill",
                            "building.2.fill",
                            "building.columns.circle.fill-1",
                            "building.columns.circle.fill",
                            "building.columns.fill",
                            "burn",
                            "bus.fill",
                            "bus",
                            "camera.fill",
                            "camera.viewfinder",
                            "candybarphone",
                            "captions.bubble.fill",
                            "car.fill",
                            "cart.circle.fill",
                            "cart.fill",
                            "cart",
                            "character.book.closed.fill",
                            "chart.pie.fill",
                            "checkerboard.rectangle",
                            "checkmark",
                            "chevron.left.forwardslash.chevron.right",
                            "chevron.up.circle",
                            "clock.fill",
                            "cloud.bolt.fill",
                            "cloud.bolt.rain.fill",
                            "cloud.rain.fill",
                            "cloud.snow.fill",
                            "comb.fill",
                            "cpu.fill",
                            "cpu",
                            "creditcard.fill",
                            "crown.fill",
                            "cube.fill",
                            "cup.and.saucer.fill",
                            "curlybraces.square.fill",
                            "cylinder.split.1x2.fill",
                            "desktopcomputer",
                            "dice.fill",
                            "die.face.1.fill",
                            "die.face.2.fill",
                            "die.face.3.fill",
                            "die.face.4.fill",
                            "die.face.5.fill",
                            "die.face.6.fill",
        ]
    }
    
    
    
    struct IconsData {
        let sectionName: String
        let data:[String]
        
    }
}
